apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    namespace: dev
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: shivanibhukya/backend-img:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-headless.dev.svc.cluster.local:27017/todos"
