apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
type: Opaque
data:
  username: bW9uZ29hZG1pbg== # Base64-encoded value of "mongoadmin"
  password: bXlwYXNzd29yZA== # Base64-encoded value of "mypassword"
